[package]
name = "chairmark"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "benchmarking library without unstable stuff"
repository = "https://github.com/Anonym234/chairmark"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdtable = "0.1.1"
